app.http.port=9301

app.db.default.type=postgresql
# app.db.default.dsn=user=postgres password=HgLpX4z9gzJWH88 host=db.gizdaappbaldvqqkfmkw.supabase.co dbname=switching port=5432 TimeZone=Asia/Jakarta
app.db.default.dsn=user=kilat password=Kitamandiricom-2025 host=192.168.192.75 dbname=va port=5432 TimeZone=Asia/Jakarta
app.db.default.poolSize=20
app.db.default.debug=true

app.env.default=prod

app.keyval.default.type=redis
app.keyval.default.url=redis://redis6_2:6379/1

app.pubsub.default.type=nats
app.pubsub.default.url=nats://nats_2:4222


app.secret.type=file
app.secret.dsn=./secret

app.log.default.level=debug
app.log.json.enabled=true
app.user.loginttl=1440


app.api.key.imgbb.credential.secret=65d90a091ab4225589f476d94ca8ec7b

 