app.http.port=9601

app.db.default.type=postgresql
app.db.default.dsn=user=kilat password=Kitamandiricom-2025 host=192.168.192.75 dbname=instant_link port=5433 TimeZone=Asia/Jakarta
app.db.default.poolSize=20
app.db.default.debug=true

app.env.default=dev

app.keyval.default.type=redis
app.keyval.default.url=redis://localhost:6379/2

app.pubsub.default.type=nats
app.pubsub.default.url=nats://localhost:4222

app.secret.type=file
app.secret.dsn=./secret

app.log.default.level=debug
app.log.json.enabled=true
app.user.loginttl=1440

app.api.key.imgbb.credential.secret=65d90a091ab4225589f476d94ca8ec7b
app.api.key.tb.credential.secret=FXDD23411

app.api.key.wa.account-id=801740719699807
app.api.key.wa.waba-id=684027611151049
app.api.key.wa.app-id=2639195729779153
app.api.key.wa.access-token=EAAlgVaP3WdEBP94UemWBIFSP7PRFjxjIuVTCGoS3vZBOpvyoE84kEBZA7vDABNLwBdnJlrX5rvNEHKmZBu7WHQVwPRnfSLv9URe4yHlfqp8zMg1JmtmsHgItcNq8JEYPsAm23Iu8g5gspDnoJrHoJ2jz6V8eX9niZA9pa3I5RkE354mZAwz3EbXWZAZA89nfwZDZD
app.http.cors=http://localhost:4200

app.api.key.groq=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
app.ai.name=KitManAI

app.workers.default=5

app.payment.auth-url=http://148.230.97.174:9301/auth/login
app.payment.login.email=user@kitamandiri.com
app.payment.login.password=Kitamandiricom-2025
app.payment.client.product-code=PDAMKABTGR
app.payment.merchant.user=ktmippob
app.payment.merchant.code=KTMIPPOB001
app.payment.category=PDAM0001
app.payment.method=PDAMTKR001
app.payment.secret-code=secret
app.payment.base-url=http://148.230.97.174:9302/api/v1
